# Generated by Django 3.1.5 on 2021-03-22 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_employee',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_employer',
            name='fullname',
            field=models.CharField(default='', max_length=100),
        ),
    ]
