# Generated by Django 3.1.5 on 2021-04-09 21:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_auto_20210407_0359'),
        ('contacts', '0002_auto_20210323_0210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_to_employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('employee_fullname', models.CharField(default='', max_length=100)),
                ('employee_phone', models.CharField(max_length=10)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('ad_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='employers.ad')),
            ],
        ),
        migrations.CreateModel(
            name='Employer_to_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('firm_name', models.CharField(max_length=100)),
                ('employer_phone', models.CharField(max_length=10)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('employer_ad', models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='employers.ad')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_employee',
        ),
        migrations.DeleteModel(
            name='Contact_employer',
        ),
    ]
