# Generated by Django 3.1.5 on 2021-04-09 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210410_0318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_to_employer',
            name='employee_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='employer_to_employee',
            name='employer_phone',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
