# Generated by Django 3.1.5 on 2021-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='salary_frequency',
            field=models.CharField(choices=[('H', 'Hourly'), ('D', 'Daily'), ('M', 'Monthly')], default='Monthly', max_length=20),
        ),
    ]
