# Generated by Django 3.1.5 on 2021-03-07 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0002_employer_salary_frequency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
    ]
