# Generated by Django 3.1.5 on 2021-03-27 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0003_auto_20210307_0537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='no_of_requirments',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='requirement',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='salary_frequency',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='salary_offered',
        ),
        migrations.RemoveField(
            model_name='employer',
            name='shift_offered',
        ),
        migrations.AlterField(
            model_name='employer',
            name='firm_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employer',
            name='match_otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_requirments', models.PositiveIntegerField(default=1)),
                ('salary_offered', models.PositiveIntegerField()),
                ('salary_frequency', models.CharField(choices=[('H', 'Hourly'), ('D', 'Daily'), ('M', 'Monthly')], default='Monthly', max_length=20)),
                ('shift_offered', models.CharField(choices=[('day', 'Day'), ('night', 'Night')], default='Day', max_length=10)),
                ('firm_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employers.employer')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employers.job')),
            ],
        ),
    ]
