# Generated by Django 3.1.5 on 2021-03-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0004_auto_20210327_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
