# Generated by Django 3.1.5 on 2021-03-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0005_ad_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='match_otp',
        ),
        migrations.AddField(
            model_name='ad',
            name='match_otp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
