# Generated by Django 3.1.5 on 2021-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0006_auto_20210330_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='salary_frequency',
            field=models.CharField(choices=[('Hourly', 'Hourly'), ('Daily', 'Daily'), ('Monthly', 'Monthly')], default='Monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='ad',
            name='shift_offered',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night'), ('Any', 'Any')], default='Day', max_length=10),
        ),
    ]
