# Generated by Django 3.1.5 on 2021-04-06 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0008_ad_create_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='firm_name',
            new_name='firm',
        ),
    ]
