# Generated by Django 3.1.5 on 2021-04-11 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0009_auto_20210407_0359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='subscription',
        ),
    ]
