# Generated by Django 3.1.5 on 2021-04-11 00:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscription_employee_subscription_employer'),
        ('employers', '0010_remove_employer_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='condition_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employer',
            name='subscription_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='employer',
            name='subscription_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.subscription_employer'),
        ),
    ]
