# Generated by Django 3.1.5 on 2021-04-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0011_auto_20210411_0545'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
    ]
