# Generated by Django 3.2 on 2021-04-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employers', '0013_alter_employer_subscription_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
