# Generated by Django 3.1.5 on 2021-02-27 21:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employers', '0001_initial'),
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('uid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=10)),
                ('phone', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('is_experienced', models.BooleanField(default=False)),
                ('prev_work_exp', models.CharField(max_length=100)),
                ('exp_salary_monthly', models.IntegerField()),
                ('pref_shift', models.CharField(choices=[('day', 'Day'), ('night', 'Night'), ('any', 'Any')], default='Day', max_length=20)),
                ('pref_location', models.CharField(max_length=50)),
                ('uid_photo_front', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('uid_photo_back', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('self_photo', models.ImageField(blank=True, default='photos/default.png', null=True, upload_to='photos/%Y/%m/%d/')),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('is_approved', models.BooleanField(default=False)),
                ('match_otp', models.IntegerField(blank=True, null=True)),
                ('rojiroti_job_num', models.IntegerField(default=0)),
                ('rojiroti_referral_code', models.CharField(blank=True, max_length=8, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('discount', models.FloatField()),
                ('subscription', models.CharField(choices=[('1st_time', '150/First time'), ('return_user', '250/Returned user')], default='150/First time', max_length=50)),
                ('referral_points', models.CharField(max_length=100)),
                ('job_preference1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jp1', to='employers.job')),
                ('job_preference2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jp2', to='employers.job')),
                ('job_preference3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='jp3', to='employers.job')),
                ('rojiroti_employer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employers.employer')),
                ('skills', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.skill')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='volunteers.volunteer')),
            ],
        ),
    ]
