# Generated by Django 3.1.5 on 2021-03-01 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skill',
            new_name='Qualification',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='skills',
            new_name='qualification',
        ),
        migrations.RenameField(
            model_name='qualification',
            old_name='skill_name',
            new_name='qualification_name',
        ),
    ]
