# Generated by Django 3.1.5 on 2021-03-01 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_auto_20210301_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='exp_salary_monthly',
            new_name='exp_salary',
        ),
        migrations.AddField(
            model_name='employee',
            name='exp_salary_frequency',
            field=models.CharField(choices=[('H', 'Hourly'), ('D', 'Daily'), ('M', 'Monthly')], default='Monthly', max_length=20),
        ),
    ]
