# Generated by Django 3.1.5 on 2021-03-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20210301_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qualification',
            name='id',
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
