# Generated by Django 3.1.5 on 2021-03-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20210302_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='qualification',
            name='qualification_description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='discount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='referral_points',
            field=models.IntegerField(default=0),
        ),
    ]
