# Generated by Django 3.1.5 on 2021-03-01 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_auto_20210302_0139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Qualification',
        ),
    ]
