# Generated by Django 3.1.5 on 2021-03-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_auto_20210302_0329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='exp_salary',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='employee',
            name='qualification',
            field=models.CharField(choices=[('8th or less', '8th or less'), ('10th', '10th or High school'), ('12th', '12th or Inter'), ('Grad and above', 'Graduation and above')], max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
