# Generated by Django 3.1.5 on 2021-03-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20210329_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='uid',
            field=models.CharField(max_length=12, primary_key=True, serialize=False),
        ),
    ]
