# Generated by Django 3.1.5 on 2021-04-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_auto_20210402_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='prev_work_exp',
            field=models.CharField(blank=True, default='Fresher', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='subscription',
            field=models.CharField(choices=[('Free', '0/Discounted'), ('1st_time', '150/First time'), ('return_user', '250/Returned user')], default='0/Discounted', max_length=50),
        ),
    ]
