# Generated by Django 3.1.5 on 2021-04-10 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20210402_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='subscription',
        ),
        migrations.AddField(
            model_name='employee',
            name='condition_agreed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='subscription_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
