# Generated by Django 3.1.5 on 2021-03-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.BigIntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
