# Generated by Django 3.1.5 on 2021-03-29 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210329_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_category',
            name='username',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
