# Generated by Django 3.1.5 on 2021-04-05 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210330_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('validity', models.CharField(default='Month', max_length=50)),
                ('feature1', models.CharField(blank=True, max_length=200)),
                ('feature2', models.CharField(blank=True, max_length=200)),
                ('feature3', models.CharField(blank=True, max_length=200)),
                ('feature4', models.CharField(blank=True, max_length=200)),
                ('feature5', models.CharField(blank=True, max_length=200)),
                ('feature6', models.CharField(blank=True, max_length=200)),
                ('feature7', models.CharField(blank=True, max_length=200)),
                ('feature8', models.CharField(blank=True, max_length=200)),
                ('feature9', models.CharField(blank=True, max_length=200)),
                ('feature10', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription_employer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('validity', models.CharField(default='Month', max_length=50)),
                ('feature1', models.CharField(blank=True, max_length=200)),
                ('feature2', models.CharField(blank=True, max_length=200)),
                ('feature3', models.CharField(blank=True, max_length=200)),
                ('feature4', models.CharField(blank=True, max_length=200)),
                ('feature5', models.CharField(blank=True, max_length=200)),
                ('feature6', models.CharField(blank=True, max_length=200)),
                ('feature7', models.CharField(blank=True, max_length=200)),
                ('feature8', models.CharField(blank=True, max_length=200)),
                ('feature9', models.CharField(blank=True, max_length=200)),
                ('feature10', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
