# Generated by Django 3.1.5 on 2021-04-13 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phoneotp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneotp',
            name='email',
        ),
        migrations.RemoveField(
            model_name='phoneotp',
            name='password',
        ),
    ]
