# Generated by Django 3.2 on 2021-04-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210414_0323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('price', models.PositiveIntegerField()),
                ('is_successful', models.BooleanField(default=False, null=True)),
            ],
        ),
    ]
