# Generated by Django 3.2 on 2021-04-26 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_order_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subscription_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
